### ISSUE TITLE
Training new model error with make_video_dataset.py

### ISSUE THREAD

**Issue by noufpy** [manuelruder/fast-artistic-videos#12]
I was able to run everything successfully on my Ubuntu 16.04 machine using CUDA 8 and CuDNN 5. However, I ran into a strange error when training a new model. 

I followed your steps and successfully finishing steps 1-5. When I reach the sixth step: 

• Run video_dataset/make_video_dataset.py --input_dir <path> --sequence_length <n>, where <path> should be identical to <output_folder> and <n> to <num_tuples_per_scene> in step 3.

I get the following error: 

```
(env) ➜ fast-artistic-videos git:(master) ✗ python video_dataset/make_video_dataset.py --input_dir /home/paperspace/fast-artistic-videos/video_dataset/output_hollywood --sequence_length 5 

Found 41023 images 
Exception in thread Thread-2: Traceback (most recent call last): 
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner 
  self.run() 
File "/usr/lib/python2.7/threading.py", line 754, in run 
  self.__target(*self.__args, **self.__kwargs) 
File "video_dataset/make_video_dataset.py", line 99, in read_worker 
  certs.append(imread(cert_path)) 
File "/home/paperspace/fast-artistic-videos/env/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread 
  im = Image.open(name) 
File "/home/paperspace/fast-artistic-videos/env/local/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open 
  fp = builtins.open(filename, "rb") 
IOError: [Errno 2] No such file or directory: '/home/paperspace/fast-artistic-videos/video_dataset/output_hollywood/scenecliptest00086/flow/reliable_4495_4494.pgm' 

Exception in thread Thread-1: Traceback (most recent call last): 
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner 
  self.run() 
File "/usr/lib/python2.7/threading.py", line 754, in run
  self.__target(*self.__args, **self.__kwargs) 
File "video_dataset/make_video_dataset.py", line 99, in read_worker 
  certs.append(imread(cert_path)) 
File "/home/paperspace/fast-artistic-videos/env/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread 
  im = Image.open(name) 
File "/home/paperspace/fast-artistic-videos/env/local/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open 
  fp = builtins.open(filename, "rb") 
IOError: [Errno 2] No such file or directory: '/home/paperspace/fast-artistic-videos/video_dataset/output_hollywood/scenecliptest00579/flow/reliable_3900_3899.pgm'
```

"Exception in Threading... No such file or directory...etc" every time I run this command. Each time, it points to a different folder with missing files.

When I check the folders specified for these missing files, I find them to be truly missing and I'm not sure where I went wrong. I followed your steps exactly as you say and I received no errors for computing optical flow and occlusions. For the first step, I used the default <num_tuples_per_scene> and <num_frames_per_tuble> which is why in step 6, I make the sequence_length 5.  

Any ideas/thoughts? I would incredibly appreciate it.

**Comment by manuelruder** [comment]
You may want to update to the latest version of this repository, then run `make_occlusions.sh` again. There was a bug where it didn't notice frame indices >3000.

Let me know if this fixed this bug.

**Comment by noufpy** [comment]
It fixed the big! Just finished running make_video_dataset.py. Thank you so much!
